spring.application.name=candidat
server.port=8082
# Activation de la console H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2

# Configuration de la source de données (Datasource)
spring.datasource.url=jdbc:h2:file:./Database/Data/Candidat;AUTO_SERVER=TRUE
spring.datasource.username=Zeineb
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.hibernate.ddl-auto=create